included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Packages

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 100
  error: 150

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 800

cyclomatic_complexity:
  warning: 15
  error: 20

identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - db
    - id
    - k1
    - b
    - tf
    - df
    - M
    - N
    - i
    - a
    - v
